version: '3'
services:
  signup-api:
    container_name: signup-api
    build:
      context: .
      args:
      - JAR_FILE=target/signup-api-0.0.1-SNAPSHOT.jar
    image: signup-api:latest
    ports:
    - "9290:9090"   # HTTP

